"""Sheet tab names and headers for Revenue Ops Copilot."""

# Tab names
LEADS_TAB = "Leads"
RUNS_TAB = "Runs"
EMAIL_DRAFTS_TAB = "Email Drafts"
IMPORTS_TAB = "Imports"
SOURCE_CANDIDATES_TAB = "Source Candidates"
ENRICHMENT_TAB = "Enrichment"

ALL_TAB_NAMES = [
    LEADS_TAB,
    RUNS_TAB,
    EMAIL_DRAFTS_TAB,
    IMPORTS_TAB,
    SOURCE_CANDIDATES_TAB,
    ENRICHMENT_TAB,
]

# Headers per tab
LEADS_HEADERS = [
    "lead_id",
    "company_name",
    "company_website",
    "company_domain",
    "company_linkedin_url",
    "prospect_name",
    "prospect_title",
    "prospect_linkedin_url",
    "prospect_email",
    "country",
    "region",
    "industry",
    "company_size",
    "technologies",
    "annual_revenue",
    "total_funding",
    "latest_funding",
    "latest_funding_amount",
    "apollo_contact_id",
    "apollo_account_id",
    "source",
    "manual_context",
    "manual_company_context",
    "manual_person_context",
    "manual_linkedin_notes",
    "manual_company_linkedin_text",
    "manual_person_linkedin_text",
    "manual_company_linkedin_copied_at",
    "manual_person_linkedin_copied_at",
    "identity_validation_status",
    "identity_validation_reason",
    "icp_status",
    "icp_score",
    "icp_score_reason",
    "ready_for_enrichment",
    "ready_for_draft",
    "source_url",
    "action",
    "status",
    "fit_score",
    "fit_score_reason",
    "quality_score",
    "quality_issues",
    "evidence_quality",
    "enrichment_result",
    "review_required",
    "review_category",
    "review_summary",
    "review_evidence",
    "suggested_action",
    "suggested_action_reason",
    "user_decision",
    "user_decision_notes",
    "manual_context_summary",
    "message_angle",
    "email_subject",
    "email_draft",
    "revision_instruction",
    "revision_instruction_hash",
    "last_processed_revision_hash",
    "revision_count",
    "revised_draft",
    "approved",
    "final_subject",
    "final_message",
    "gmail_draft_id",
    "gmail_draft_url",
    "export_ready",
    "agent_note",
    "error_message",
    "run_id",
    "locked_at",
    "processed_at",
    "last_updated_by_agent_at",
]

RUNS_HEADERS = [
    "run_id",
    "started_at",
    "finished_at",
    "source",
    "sheet_id",
    "created_by",
    "status",
    "total_rows",
    "success_count",
    "error_count",
    "skipped_count",
    "drafts_created",
    "batch_limit",
    "notes",
]

EMAIL_DRAFTS_HEADERS = [
    "run_id",
    "lead_id",
    "created_at",
    "company_name",
    "prospect_name",
    "prospect_title",
    "prospect_email",
    "email_subject",
    "gmail_draft_id",
    "gmail_draft_url",
    "approved",
    "sent_manually",
    "sent_at",
    "reply_status",
    "notes",
]

IMPORTS_HEADERS = [
    "import_batch_id",
    "source_provider",
    "source_type",
    "file_name",
    "created_by",
    "created_at",
    "total_rows",
    "imported_count",
    "duplicate_count",
    "rejected_count",
    "error_count",
    "status",
    "notes",
]

SOURCE_CANDIDATES_HEADERS = [
    "candidate_id",
    "source_provider",
    "source_record_id",
    "source_url",
    "company_name",
    "company_website",
    "company_domain",
    "company_linkedin_url",
    "prospect_name",
    "prospect_title",
    "prospect_linkedin_url",
    "prospect_email",
    "country",
    "region",
    "industry",
    "company_size",
    "raw_headline",
    "raw_company_description",
    "raw_data_json",
    "candidate_status",
    "candidate_score",
    "candidate_score_reason",
    "apollo_enrichment_status",
    "apollo_enrichment_reason",
    "apollo_enrichment_score",
    "apollo_enrichment_confidence",
    "apollo_email_enriched_at",
    "apollo_credits_used",
    "manual_company_linkedin_text",
    "manual_person_linkedin_text",
    "manual_company_linkedin_copied_at",
    "manual_person_linkedin_copied_at",
    "identity_validation_status",
    "identity_validation_reason",
    "icp_status",
    "icp_score",
    "icp_score_reason",
    "ready_for_enrichment",
    "ready_for_draft",
    "dedupe_key",
    "duplicate_of",
    "import_batch_id",
    "created_at",
    "reviewed_by",
    "reviewed_at",
    "notes",
]

ENRICHMENT_HEADERS = [
    "enrichment_id",
    "run_id",
    "lead_id",
    "company_name",
    "company_website",
    "company_domain",
    "company_linkedin_url",
    "prospect_name",
    "prospect_title",
    "prospect_linkedin_url",
    "country",
    "industry",
    "company_size",
    "enrichment_status",
    "company_summary",
    "b2b_fit",
    "operational_pain_hypothesis",
    "possible_ai_use_case",
    "personalization_angle",
    "trigger_summary",
    "risk_flags",
    "review_required",
    "review_category",
    "review_summary",
    "review_evidence",
    "suggested_action",
    "suggested_action_reason",
    "user_decision",
    "user_decision_notes",
    "evidence_count",
    "evidence_sources",
    "evidence_summary",
    "evidence_urls",
    "confidence_score",
    "recommended_action",
    "created_at",
    "finished_at",
    "error_message",
]

TAB_HEADERS: dict[str, list[str]] = {
    LEADS_TAB: LEADS_HEADERS,
    RUNS_TAB: RUNS_HEADERS,
    EMAIL_DRAFTS_TAB: EMAIL_DRAFTS_HEADERS,
    IMPORTS_TAB: IMPORTS_HEADERS,
    SOURCE_CANDIDATES_TAB: SOURCE_CANDIDATES_HEADERS,
    ENRICHMENT_TAB: ENRICHMENT_HEADERS,
}
